import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new', args:['--use-angle=metal','--enable-gpu'] })
const page = await b.newPage(); await page.setViewport({ width: 1024, height: 700 })
await page.goto('http://localhost:5173', { waitUntil:'domcontentloaded' }); await new Promise(r=>setTimeout(r,3000))
await page.evaluate(()=>{localStorage.removeItem('nightgarage.ghost');localStorage.removeItem('nightgarage.bestLap')})
await page.reload({waitUntil:'domcontentloaded'}); await new Promise(r=>setTimeout(r,7000))
await page.evaluate(()=>window.__enterCar && window.__enterCar(0)); await new Promise(r=>setTimeout(r,600))
await page.evaluate(()=>window.__drive && window.__drive(0)); await new Promise(r=>setTimeout(r,900))
await page.evaluate(()=>window.__place && window.__place(0,108,16)); await new Promise(r=>setTimeout(r,300))
await page.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,1500)); await page.keyboard.up('KeyW')
await new Promise(r=>setTimeout(r,4000))
await page.evaluate(()=>window.__place && window.__place(0,108,16)); await new Promise(r=>setTimeout(r,300))
await page.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,2000)); await page.keyboard.up('KeyW')
const msg = await page.evaluate(()=>({text:document.getElementById('lap-msg')?.textContent, cls:document.getElementById('lap-msg')?.className, count:document.getElementById('lap-count')?.textContent}))
console.log('after ghost set:', JSON.stringify(msg))
await b.close()
