import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new', args:['--use-angle=metal','--enable-gpu'] })
const page = await b.newPage(); const errs=[]; page.on('pageerror',e=>errs.push(String(e).slice(0,120)))
await page.setViewport({ width: 1000, height: 700 })
await page.goto('http://localhost:5173', { waitUntil:'domcontentloaded' }); await new Promise(r=>setTimeout(r,7000))
await page.evaluate(() => { const el=[...document.querySelectorAll('div')].find(x=>getComputedStyle(x).overflowY==='auto'); if(el)el.scrollTop=el.scrollHeight }); await new Promise(r=>setTimeout(r,2500))
await page.evaluate(()=>document.querySelector('.ctl-step')?.click()); await new Promise(r=>setTimeout(r,800))
await page.keyboard.press('KeyE'); await new Promise(r=>setTimeout(r,900))
const s=()=>page.evaluate(()=>({spd:document.getElementById('spd-num')?.textContent, fwd:window.__car?+window.__car.fwd.toFixed(1):null}))
console.log('CAR (auto default) — hold W only:')
await page.keyboard.down('KeyW'); for(let i=0;i<4;i++){ await new Promise(r=>setTimeout(r,350)); console.log(await s()) } await page.keyboard.up('KeyW')
console.log('now S to reverse:')
await new Promise(r=>setTimeout(r,700))
await page.keyboard.down('KeyS'); for(let i=0;i<5;i++){ await new Promise(r=>setTimeout(r,350)); console.log(await s()) } await page.keyboard.up('KeyS')
console.log('errors:', errs.slice(0,2))
await b.close()
