import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal','--enable-gpu'] })
// DESKTOP: buttons hidden, V cycles view, horn/view events don't error
const d = await b.newPage(); const de=[]; d.on('pageerror',e=>de.push(String(e).slice(0,100)))
await d.setViewport({ width: 1280, height: 800 })
await d.goto('http://localhost:5173', { waitUntil:'domcontentloaded' }); await new Promise(r=>setTimeout(r,4500))
await d.evaluate(() => { const el=[...document.querySelectorAll('div')].find(x=>getComputedStyle(x).overflowY==='auto'); if(el)el.scrollTop=el.scrollHeight }); await new Promise(r=>setTimeout(r,2500))
await d.mouse.move(120,400); await d.evaluate(()=>document.querySelector('.ctl-step')?.click()); await new Promise(r=>setTimeout(r,800))
await d.keyboard.press('KeyE'); await new Promise(r=>setTimeout(r,1000))
console.log('DESKTOP action buttons present?', await d.evaluate(()=>({flash:!!document.querySelector('.ctl-flash'), view:!!document.querySelector('.ctl-viewcam'), horn:!!document.querySelector('.ctl-honk')})))
await d.keyboard.press('KeyI'); await new Promise(r=>setTimeout(r,300))
await d.keyboard.down('ShiftLeft'); await d.keyboard.press('ArrowUp'); await d.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,600)); await d.keyboard.up('ShiftLeft'); await new Promise(r=>setTimeout(r,700))
await d.screenshot({ path:'scripts/cam-chase.png' })
await d.evaluate(()=>window.dispatchEvent(new Event('drive-cam'))); await new Promise(r=>setTimeout(r,700))
await d.screenshot({ path:'scripts/cam-close.png' })
await d.evaluate(()=>window.dispatchEvent(new Event('drive-cam'))); await new Promise(r=>setTimeout(r,700))
await d.screenshot({ path:'scripts/cam-hood.png' })
await d.evaluate(()=>window.dispatchEvent(new Event('vehicle-horn')))
await new Promise(r=>setTimeout(r,300))
console.log('DESKTOP errors:', de.slice(0,3))
await d.keyboard.up('KeyW')
// MOBILE: buttons present + size
const m = await b.newPage()
await m.evaluateOnNewDocument(() => { const o=window.matchMedia.bind(window); window.matchMedia=(q)=>/pointer: coarse|hover: none/.test(q)?{matches:true,media:q,onchange:null,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){},dispatchEvent(){return false}}:o(q) })
await m.setViewport({ width: 900, height: 450, hasTouch:true, isMobile:true, deviceScaleFactor:2 })
await m.goto('http://localhost:5173', { waitUntil:'domcontentloaded' }); await new Promise(r=>setTimeout(r,4500))
await m.evaluate(() => { const el=[...document.querySelectorAll('div')].find(x=>getComputedStyle(x).overflowY==='auto'); if(el)el.scrollTop=el.scrollHeight }); await new Promise(r=>setTimeout(r,2500))
await m.evaluate(()=>document.querySelector('.ctl-step')?.click()); await new Promise(r=>setTimeout(r,3000))
await m.evaluate(()=>{ const el=[...document.querySelectorAll('*')].find(e=>e.children.length===0 && /drive the civic/i.test(e.textContent)); if(el)(el.closest('.aim-label,.sit-label')||el).click() }); await new Promise(r=>setTimeout(r,1200))
console.log('MOBILE buttons:', await m.evaluate(()=>{ const f=document.querySelector('.ctl-flash'); return {flash:!!f, view:!!document.querySelector('.ctl-viewcam'), horn:!!document.querySelector('.ctl-honk'), w: f?Math.round(f.getBoundingClientRect().width):null} }))
await b.close()
