import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal','--enable-gpu'] })
const page = await b.newPage(); const errs=[]; page.on('pageerror',e=>errs.push(String(e).slice(0,120)))
await page.setViewport({ width: 1280, height: 800 })
await page.goto('http://localhost:5173', { waitUntil: 'domcontentloaded' })
await new Promise(r=>setTimeout(r,4500))
await page.evaluate(() => { const el=[...document.querySelectorAll('div')].find(d=>getComputedStyle(d).overflowY==='auto'); if(el)el.scrollTop=el.scrollHeight })
await new Promise(r=>setTimeout(r,2500))
await page.mouse.move(120,400)
await page.evaluate(()=>document.querySelector('.ctl-step')?.click())
await new Promise(r=>setTimeout(r,800))
await page.keyboard.press('KeyE'); await new Promise(r=>setTimeout(r,700))
const hud = () => page.evaluate(()=>({gear:document.getElementById('gear-num')?.textContent, warn:document.getElementById('rev-warn')?.textContent, spd:document.getElementById('spd-num')?.textContent, car:window.__car?{z:+window.__car.z.toFixed(1),fwd:+window.__car.fwd.toFixed(1)}:null}))
console.log('after E:', await hud())
await page.keyboard.press('KeyI'); await new Promise(r=>setTimeout(r,400))
console.log('after I:', await hud())
await page.keyboard.down('ShiftLeft'); await page.keyboard.press('ArrowUp'); await page.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,700)); await page.keyboard.up('ShiftLeft')
await new Promise(r=>setTimeout(r,800))
console.log('after launch:', await hud())
await new Promise(r=>setTimeout(r,800))
console.log('later:', await hud())
console.log('errors:', errs)
await b.close()
