import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new', args:['--use-angle=metal','--enable-gpu'] })
const page = await b.newPage(); await page.setViewport({ width: 1024, height: 700 })
const errs=[]; page.on('pageerror',e=>errs.push(String(e)))
await page.goto('http://localhost:5173', { waitUntil:'domcontentloaded' }); await new Promise(r=>setTimeout(r,3000))
await page.evaluate(()=>{localStorage.removeItem('nightgarage.ghost');localStorage.removeItem('nightgarage.bestLap')})
await page.reload({waitUntil:'domcontentloaded'}); await new Promise(r=>setTimeout(r,7000))
await page.evaluate(()=>window.__enterCar && window.__enterCar(0)); await new Promise(r=>setTimeout(r,600))
await page.evaluate(()=>window.__drive && window.__drive(0)); await new Promise(r=>setTimeout(r,900))
const hud=()=>page.evaluate(()=>({cur:document.getElementById('lap-cur')?.textContent,last:document.getElementById('lap-last')?.textContent,count:document.getElementById('lap-count')?.textContent}))
// crossing 1: arm the timer
await page.evaluate(()=>window.__place && window.__place(0,108,16)); await new Promise(r=>setTimeout(r,300))
await page.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,1500)); await page.keyboard.up('KeyW')
console.log('after crossing 1 (arm):', JSON.stringify(await hud()))
const ghostAfter1 = await page.evaluate(()=>!!localStorage.getItem('nightgarage.ghost'))
// keep "lapping": teleport back and drive across again >3s later
await page.evaluate(()=>window.__place && window.__place(0,108,16)); await new Promise(r=>setTimeout(r,300))
await page.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,4500)); await page.keyboard.up('KeyW')
console.log('after crossing 2 (complete lap):', JSON.stringify(await hud()))
const g = await page.evaluate(()=>{const s=localStorage.getItem('nightgarage.ghost'); if(!s)return null; const o=JSON.parse(s); return {samples:o.samples?.length, sectors:o.sectors}})
console.log('ghost saved to storage?', g?`YES (${g.samples} samples)`:'NO')
console.log('bestLap:', await page.evaluate(()=>localStorage.getItem('nightgarage.bestLap')))
console.log('errs:', errs.length, errs.slice(0,2).join(' | '))
await b.close()
