import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal', '--enable-gpu'] })
const page = await b.newPage()
await page.setViewport({ width: 1280, height: 800 })
await page.goto('http://localhost:5173', { waitUntil: 'domcontentloaded' })
await new Promise((r) => setTimeout(r, 4500))
await page.evaluate(() => { const el=[...document.querySelectorAll('div')].find(d=>getComputedStyle(d).overflowY==='auto'); el.scrollTop=el.scrollHeight })
await new Promise((r) => setTimeout(r, 2500))
await page.mouse.move(100,400)
await page.evaluate(() => document.querySelector('.ctl-step')?.click())
await new Promise((r) => setTimeout(r, 700))
await page.keyboard.press('KeyE')
await new Promise(r=>setTimeout(r,700))
const read = () => page.evaluate(() => ({ g: document.getElementById('gear-num')?.textContent, spd:+document.getElementById('spd-num')?.textContent, warn: document.getElementById('rev-warn')?.textContent, help: !!document.querySelector('.drive-help') }))
console.log('boarded (off, N):', await read())
// shift to 1st then start IN GEAR -> should lurch (spd jumps) and stay off
await page.keyboard.press('ArrowUp')
await new Promise(r=>setTimeout(r,200))
console.log('shifted to 1:', await read())
await page.keyboard.press('KeyI')
await new Promise(r=>setTimeout(r,150))
console.log('start in gear (expect lurch, spd>0, still off):', await read())
await new Promise(r=>setTimeout(r,1500))
console.log('after lurch settles:', await read())
// proper start: neutral (down to N), I, then launch
await page.keyboard.press('ArrowDown')
await page.keyboard.press('KeyI')
await new Promise(r=>setTimeout(r,300))
console.log('started in N:', await read())
await page.keyboard.down('ShiftLeft'); await page.keyboard.press('ArrowUp')
await page.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,700))
await page.keyboard.up('ShiftLeft'); await new Promise(r=>setTimeout(r,1200))
console.log('clutch launch:', await read())
await page.keyboard.up('KeyW')
await b.close()
