import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal','--enable-gpu'] })
const page = await b.newPage()
await page.setViewport({ width: 1280, height: 800 })
await page.goto('http://localhost:5173', { waitUntil:'domcontentloaded' }); await new Promise(r=>setTimeout(r,4500))
await page.evaluate(() => { const el=[...document.querySelectorAll('div')].find(x=>getComputedStyle(x).overflowY==='auto'); if(el)el.scrollTop=el.scrollHeight }); await new Promise(r=>setTimeout(r,2500))
await page.mouse.move(120,400); await page.evaluate(()=>document.querySelector('.ctl-step')?.click()); await new Promise(r=>setTimeout(r,1000))
const bulbs = () => page.evaluate(()=>[...document.querySelectorAll('button')].filter(b=>b.textContent.includes('💡')).map(b=>b.className))
console.log('EXPLORE 💡 buttons:', await bulbs(), '| lights btn present:', await page.evaluate(()=>!!document.querySelector('.ctl-lights')))
await page.keyboard.press('KeyE'); await new Promise(r=>setTimeout(r,1000))
console.log('DRIVE   💡 buttons:', await bulbs(), '| lights btn present:', await page.evaluate(()=>!!document.querySelector('.ctl-lights')))
await b.close()
