import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--window-size=1280,800'] })
const page = await b.newPage()
await page.goto('http://localhost:5173', { waitUntil: 'domcontentloaded' })
await new Promise((r) => setTimeout(r, 3500))
const icon = () => page.evaluate(() => document.querySelector('.ctl-lights')?.textContent)
console.log('initial:', await icon())
await page.keyboard.press('KeyL')
await new Promise((r) => setTimeout(r, 300))
console.log('after L:', await icon())
await page.screenshot({ path: '/tmp/shots/18-night.png' })
await page.keyboard.press('KeyL')
await new Promise((r) => setTimeout(r, 300))
console.log('after L again:', await icon())
await b.close()
