import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal', '--enable-gpu'] })
const page = await b.newPage()
const errs=[]; page.on('pageerror',e=>errs.push(String(e).slice(0,140)))
await page.setViewport({ width: 1280, height: 800 })
await page.goto('http://localhost:5173', { waitUntil: 'domcontentloaded' })
await new Promise((r) => setTimeout(r, 4500))
await page.evaluate(() => document.querySelector('.ctl-phys')?.click()) // physics ON
await new Promise((r) => setTimeout(r, 400))
await page.evaluate(() => { const el=[...document.querySelectorAll('div')].find(d=>getComputedStyle(d).overflowY==='auto'); el.scrollTop=el.scrollHeight })
await new Promise((r) => setTimeout(r, 2500))
await page.mouse.move(100,400)
await page.evaluate(() => document.querySelector('.ctl-step')?.click())
await new Promise((r) => setTimeout(r, 800))
await page.keyboard.press('KeyE'); await new Promise(r=>setTimeout(r,800))
const read = () => page.evaluate(() => ({ g: document.getElementById('gear-num')?.textContent, spd:+document.getElementById('spd-num')?.textContent, warn: document.getElementById('rev-warn')?.textContent }))
console.log('boarded:', await read())
// start + clutch launch
await page.keyboard.press('KeyI'); await new Promise(r=>setTimeout(r,300))
console.log('started:', await read())
await page.keyboard.down('ShiftLeft'); await page.keyboard.press('ArrowUp')
await page.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,700))
await page.keyboard.up('ShiftLeft'); await new Promise(r=>setTimeout(r,600))
console.log('launched:', await read())
// wind out, upshift at redline
for (let s=0;s<12;s++){ await new Promise(r=>setTimeout(r,500)); const rpm=await page.evaluate(()=>parseInt(document.getElementById('rpm-fill')?.style.width)); const r=await read(); if(rpm>92 && r.g!=='5') await page.keyboard.press('ArrowUp'); if(s%2===0) console.log('wind',s,r,'rpm'+rpm); if(r.spd>90) break }
console.log('TOP:', await read())
await page.keyboard.up('KeyW')
const fps = await page.evaluate(() => new Promise((res)=>{let n=0;const t0=performance.now();const t=()=>(performance.now()-t0<2000?(n++,requestAnimationFrame(t)):res(Math.round(n/2)));requestAnimationFrame(t)}))
console.log('fps:', fps, 'errors:', errs.slice(0,3))
await b.close()
