import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal', '--enable-gpu'] })
const page = await b.newPage()
const errs=[]; page.on('pageerror',e=>errs.push(String(e).slice(0,140)))
await page.setViewport({ width: 1280, height: 800 })
await page.goto('http://localhost:5173', { waitUntil: 'domcontentloaded' })
await new Promise((r) => setTimeout(r, 4500))
// enable physics mode
await page.evaluate(() => document.querySelector('.ctl-phys')?.click())
await new Promise((r) => setTimeout(r, 400))
console.log('mode btn:', await page.evaluate(()=>document.querySelector('.ctl-phys')?.textContent))
await page.evaluate(() => { const el=[...document.querySelectorAll('div')].find(d=>getComputedStyle(d).overflowY==='auto'); el.scrollTop=el.scrollHeight })
await new Promise((r) => setTimeout(r, 2500))
await page.mouse.move(100,400)
await page.evaluate(() => document.querySelector('.ctl-step')?.click())
await new Promise((r) => setTimeout(r, 800))
await page.keyboard.press('KeyE'); await new Promise(r=>setTimeout(r,900))
const read = () => page.evaluate(() => ({ g: document.getElementById('gear-num')?.textContent, spd:+document.getElementById('spd-num')?.textContent }))
console.log('boarded (physics):', await read())
await page.keyboard.down('KeyW')
for (let s=0;s<6;s++){ await new Promise(r=>setTimeout(r,600)); console.log('drive',s,await read()) }
await page.keyboard.up('KeyW')
const fps = await page.evaluate(() => new Promise((res)=>{let n=0;const t0=performance.now();const t=()=>(performance.now()-t0<2000?(n++,requestAnimationFrame(t)):res(Math.round(n/2)));requestAnimationFrame(t)}))
console.log('fps:', fps)
console.log('errors:', errs.slice(0,4))
await b.close()
