import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal','--enable-gpu'] })
const page = await b.newPage()
await page.setViewport({ width: 1280, height: 800 })
await page.goto('http://localhost:5173', { waitUntil: 'domcontentloaded' })
await new Promise(r=>setTimeout(r,4500))
await page.evaluate(() => { const el=[...document.querySelectorAll('div')].find(d=>getComputedStyle(d).overflowY==='auto'); if(el)el.scrollTop=el.scrollHeight })
await new Promise(r=>setTimeout(r,2500))
await page.mouse.move(120,400)
await page.evaluate(()=>document.querySelector('.ctl-step')?.click())
await new Promise(r=>setTimeout(r,800))
await page.keyboard.press('KeyE'); await new Promise(r=>setTimeout(r,1200))
await page.screenshot({ path: 'scripts/tune-left.png' })
const box = await page.evaluate(()=>{ const t=document.querySelector('.tune'); if(!t)return null; const r=t.getBoundingClientRect(); return {left:Math.round(r.x),top:Math.round(r.y),right:Math.round(r.right),bottom:Math.round(r.bottom)} })
console.log('tune box:', JSON.stringify(box))
await b.close()
